pass through wav/aiff support from id3.
TianyiShi2001/audiotags pull request #47
Opened 2024-05-22 21:18 UTC by jct-tympanon

id3 added format detection logic to Tag::read_from_path, so the same API now works for mp3/wav/aiff.  the only thing needed was a version bump and some test cases.

the existing a.wav asset had no tag chunk in it, which caused the existing test case to fail (the other assets have empty or trivial tags). so a.wav and a.aif both have empty tag chunks to start with.

https://github.com/TianyiShi2001/audiotags/issues/22

2024-05-23 01:50 UTC, lukethacoder approved these changes
Keen to see this one merged ❤️

2026-08-25 01:10 UTC, pinkforest commented
@Serial-ATA opinion on this? probably needs a refresh

2026-08-25 02:40 UTC, Serial-ATA requested changes

2026-08-25 02:40 UTC, Serial-ATA commented on src/lib.rs
> +                            "aif" | "aiff" | "mp3" | "wav" => Ok(Self::Id3v2),
```suggestion
                            "aif" | "aiff" | "aifc" | "mp3" | "wav" => Ok(Self::Id3v2),
```

`aifc` is also a common extension

2026-08-25 02:40 UTC, Serial-ATA commented on Cargo.toml
> +id3 = "1.13.1"
```suggestion
id3 = "1.17.1"
```

2026-08-25 02:41 UTC, Serial-ATA commented
@pinkforest just a couple small comments, but this is also fine as-is

2026-08-26 00:31 UTC, pinkforest commented
Looks like smol clippy round but it's unrelated can be done separately

2026-08-26 00:32 UTC, merged